assignment3: ShelterBST.o assignment3.cpp
	g++ assignment3.cpp ShelterBST.o -std=c++11 -Wall -g -o assignment3

ShelterBST.o: ShelterBST.h ShelterBST.cpp
	g++ -c -Wall -Werror -pedantic -std=c++11 ShelterBST.cpp